######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 14:26:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lpcap
QT += network

# Input
HEADERS += qpcap.h qpcappacket.h
SOURCES += main.cpp qpcap.cpp qpcappacket.cpp
